### ISSUE TITLE
exists?

### ISSUE THREAD

**Issue by pupeno** [budu/lobos#10]
Hello,

I would find it useful if Lobos provided an exists? method that would return true if the table already exists and false otherwise.

Thanks.

**Comment by budu** [comment]
I'm not sure about adding a function with such a generic name. You can always use the analyzer to do that and maybe create your own function:

```
(use 'lobos.analyze)

(defn table-exists? [conn-info table-name]
  (-> conn-info analyze-schema :elements table-name)
```

In that example, the table name must be a keyword and it search only in the default schema. You can use the analyze-schema as a generic `exists?` function, this is especially powerful when used with the `-?>` macro, ex.:

```
user=> (-?> conn-info analyze-schema :elements :foo :indexes :bar)
```

This will return `nil` either if the table 'foo' is missing or if there's no 'bar' index defined on it.
