### ISSUE TITLE
Namespaces on the documentation

### ISSUE THREAD

**Issue by pupeno** [budu/lobos#11]
Hello,

In the documentation you are using "use" to load the different namespaces of Lobos. I think a good practice is to use require :as, so you know where things are coming from, but in the documentation, I think it'd be nice to show where things are coming from.

Thanks.

**Comment by budu** [comment]
That might be a good idea, although I'm mostly doing that to tone down the noise and focus on Lobos specific features. I'll probably revisit the documentation before releasing version 0.8 and will reconsider this suggestion. Thanks

**Comment by pupeno** [comment]
Maybe an alternative would be to specify each var in the use statement, but
now that I used lobos more information can see how use could make sense. For
the migration and schema parts, I think it's fine, because it's isolated to
a file. For the querying language I would go to require instead of use.

## 

J. Pablo Fernández <pupeno.com> (http://pupeno.com)
On 18 Aug 2011 07:24, "budu" <
reply@reply.github.com>
wrote:
