### ISSUE TITLE
Migrations do not work in 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by jsyrjala** [budu/lobos#27]
I am getting following exception in 1.0.0-SNAPSHOT. This doesn't happen in 0.8.0.

Note that missing file is called lobos/migrations.clj, there is lobos/migration.clj file inside lobos.jar.

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate lobos/migrations__init.class or lobos/migrations.clj on classpath: 

My test program is like this:

```
(ns db.lobostest
  (:refer-clojure :exclude [alter drop
                        bigint boolean char double float time complement])
  (:use (lobos [migration :only [defmigration]] connectivity core schema))
  )

(def database-config
    {:classname "org.postgresql.Driver"
     :subprotocol "postgresql"
     :user "xxx"
     :password "xxx"
     :subname "//localhost/xxx"})

(defmigration add-new-table
  (up [] (create
          (table :foobar
               (timestamp :stamp)
               )))
  (down [] (drop (table :foobar)))) 


(defn -main []
 (open-global database-config)
  (println "Migration start")
  (migrate)
  (println "Migration end")
)
```

**Comment by budu** [comment]
There have been some changes so that the migrations get loaded automatically when calling a migration command so that only the core namespace is required, thus your code is not working anymore. Try to follow the documentation in the readme file.

**Comment by budu** [comment]
Also if you want to be able to call migration from outside a REPL, check out the Leiningen plugin: https://github.com/pupeno/lein-lobos

**Comment by jsyrjala** [comment]
I modified my code to inside namespace lobos.migrations and it started to work. Maybe the readme should be more explicit about this. I thought that the filenames and namespaces used in readme where just examples, and could be altered.

**Comment by budu** [comment]
Yeah that's a problem with the current readme, I'll try to make this detail more explicit. Also the migrations namespace can be changed, it can be found in the `lobos.migration/*migrations-namespace*` dynamic variable.

**Comment by piyushmandovra** [comment]
yeah I wasted lot of time for same and then googled it and got existing issue.
