### ISSUE TITLE
:auto-inc with Postgres creates a sequence, not a SERIAL field

### ISSUE THREAD

**Issue by jsyrjala** [budu/lobos#30]
Maybe _:auto-inc_ should create a serial field with Postgres ( http://www.postgresql.org/docs/8.1/static/datatype.html )

```
  (integer table :id :auto-inc :primary-key))
```

Results to these:

```
CREATE TABLE some_table (
    id integer NOT NULL,
```

and 

```
CREATE SEQUENCE some_table_id_seq
```

The _id_ field should have this default value in addition: *DEFAULT nextval('some_table_id_seq') *

**Comment by budu** [comment]
Well, it should already be doing that. After testing it and dusting off the debug function, it seems I'm unable to reproduce your issue:

``` clojure
(debug build-create-statement (table :foo (integer :id :auto-inc :primary-key)) [] :sql)
"CREATE TABLE \"foo\" (\"id\" SERIAL, CONSTRAINT \"foo_primary_key_id\" PRIMARY KEY (\"id\"))"
```
