### ISSUE TITLE
Documentation/examples should also show how to create indexes and alter tables

### ISSUE THREAD

**Issue by jsyrjala** [budu/lobos#33]
How about adding some examples on how to create indexes and how to alter existing tables (by adding a column etc)?

**Comment by budu** [comment]
Yes, there were some examples in the previous readme file, but when I rewrote it I decided to keep it short. There's some examples in the documentation page of the current website: http://budu.github.com/lobos/documentation.html

P.S.: I'm working on a more comprehensive documentation for the new website, there's still a couple of things to be done before it's releasable.

**Comment by jsyrjala** [comment]
Ah, didn't notice that lobos has a separate website. The readme should definitely link to website.
