### ISSUE TITLE
unique index creation on 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by techwhizbang** [budu/lobos#37]
Creating a unique index like so

(index :some_table [:app_id :email_address] :unique)

yields an error if you don't specify the index name...

"Don't know how to create ISeq from: clojure.lang.Keyword"

**Comment by budu** [comment]
Good catch, it seems I had been lazy while writing that function! The name argument is now optional and I've even took the opportunity to add tests and documentation. Should be in the next snapshot later today.

**Comment by techwhizbang** [comment]
Thank you for the update.
