### ISSUE TITLE
Executing run or rollback after running dump, throws an exception.

### ISSUE THREAD

**Issue by mmwaikar** [budu/lobos#4]
Basically you should get this error, if you try to execute (any of) run, rollback or dump once the "lobos_migrations" table has been created previously (through the use of, say dump).

I am using Postgresql DB. (driver 9.0-801.jdbc4).

Here is the stack trace -

ERROR: relation "lobos_migrations" already exists
  [Thrown class org.postgresql.util.PSQLException]

Restarts:
 0: [QUIT] Quit to the SLIME top level

Backtrace:
  0: org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
  1: org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
  2: org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
  3: org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
  4: org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
  5: org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:366)
  6: sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  7: sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  8: sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  9: java.lang.reflect.Method.invoke(Method.java:597)
 10: clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
      [No Locals]
 11: clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
 12: lobos.internal$execute_STAR_$fn__3944.invoke(internal.clj:34)
 13: lobos.internal$execute_STAR_.invoke(internal.clj:33)
 14: lobos.internal$execute$fn__3953.invoke(internal.clj:55)
 15: lobos.connectivity$with_spec_connection.invoke(connectivity.clj:126)
 16: lobos.internal$execute.doInvoke(internal.clj:47)
 17: clojure.lang.RestFn.invoke(RestFn.java:424)
 18: lobos.migration$create_migrations_table.invoke(migration.clj:170)
 19: lobos.core$rollback.doInvoke(core.clj:198)
 20: clojure.lang.RestFn.invoke(RestFn.java:409)
 21: user$eval5940.invoke(NO_SOURCE_FILE:1)
 22: clojure.lang.Compiler.eval(Compiler.java:5424)
 23: clojure.lang.Compiler.eval(Compiler.java:5391)
 24: clojure.core$eval.invoke(core.clj:2382)
 25: swank.commands.basic$eval_region.invoke(basic.clj:47)
 26: swank.commands.basic$eval_region.invoke(basic.clj:37)
 27: swank.commands.basic$eval810$listener_eval__811.invoke(basic.clj:71)
 28: clojure.lang.Var.invoke(Var.java:365)
 29: user$eval5938.invoke(NO_SOURCE_FILE)
 30: clojure.lang.Compiler.eval(Compiler.java:5424)
 31: clojure.lang.Compiler.eval(Compiler.java:5391)
 32: clojure.core$eval.invoke(core.clj:2382)
 33: swank.core$eval_in_emacs_package.invoke(core.clj:94)
 34: swank.core$eval_for_emacs.invoke(core.clj:241)
 35: clojure.lang.Var.invoke(Var.java:373)
 36: clojure.lang.AFn.applyToHelper(AFn.java:169)
 37: clojure.lang.Var.applyTo(Var.java:482)
 38: clojure.core$apply.invoke(core.clj:540)
 39: swank.core$eval_from_control.invoke(core.clj:101)
 40: swank.core$eval_loop.invoke(core.clj:106)
 41: swank.core$spawn_repl_thread$fn__492$fn__493.invoke(core.clj:311)
 42: clojure.lang.AFn.applyToHelper(AFn.java:159)
 43: clojure.lang.AFn.applyTo(AFn.java:151)
 44: clojure.core$apply.invoke(core.clj:540)
 45: swank.core$spawn_repl_thread$fn__492.doInvoke(core.clj:308)
 46: clojure.lang.RestFn.invoke(RestFn.java:398)
 47: clojure.lang.AFn.run(AFn.java:24)
 48: java.lang.Thread.run(Thread.java:662)

**Comment by budu** [comment]
What did you pass as `dump` arguments? What does the db-spec used contains?

**Comment by budu** [comment]
Should be fixed with db38bedee28b6f2c322f499e2f5cb97d2b7c07dc
