### ISSUE TITLE
Not able to generate serial column for Postgres

### ISSUE THREAD

**Issue by davejacobs** [budu/lobos#56]
Similar to https://github.com/budu/lobos/issues/30, I'm unable to generate an autoincrementing serial column using the `(tbl)` macro in my Postgres migrations.

After using the macro to generate a table, the schema looks like the following:

```
    Column     |            Type             |                     Modifiers                      
----------------+-----------------------------+----------------------------------------------------
 id             | integer                     | not null default nextval('users_id_seq'::regclass)
 type           | character varying(255)      | 
 email          | character varying(255)      |
...
```

Using debug per the instructions in issue 30:

``` clojure
(debug build-create-statement (table :foo (integer :id :auto-inc :primary-key)) [] :sql)

;=> "CREATE TABLE \"foo\" (\"id\" INTEGER GENERATED ALWAYS AS IDENTITY, CONSTRAINT \"foo_primary_key_id\" PRIMARY KEY (\"id\"))"
```

Inspecting the result of `(integer)`:

``` clojure
(integer (table :users) :id :auto-inc :primary-key))
;=> 
{:name :users,
 :columns
 {:id
  {:cname :id,
   :data-type {:name :integer, :args [], :options {}},
   :default nil,
   :auto-inc true,
   :not-null nil,
   :others ()}},
 :constraints
 {:users_primary_key_id
  {:cname :users_primary_key_id, :ctype :primary-key, :columns [:id]}},
 :indexes {}}
```

I'm using Lobos 1.0.0-beta1.

What am I missing?

**Comment by lispwright** [comment]
From: David Jacobs notifications@github.com
  Date: Tue, 26 Feb 2013 11:25:35 -0800

  [ Details omitted for now. ]

  I'm using Lobos 1.0.0-beta1.

So am I.

  What am I missing?

Don't know; I got this to working without difficultly, here are my
higher level details:

Debian squeeze.
PostgreSQL 9.2 from their Debian repository.

My tbl macro:

(defmacro tbl [name & elements]
  `(-> (table ~name)
       ~@(reverse elements)
       (surrogate-key)))

A working defmigration; table, column and user names
mechanically changed protect the innocent:

(defmigration add-foos-table
  (up [](create
          %28tbl :foos
               %28varchar :foo 64 :unique%29
               %28check :foo %28> %28length :foo%29 1%29%29%29))
  (down [](drop %28table :foos%29)))

The output of \d

```
            List of relations
```

 Schema |        Name         |   Type   | Owner 
--------+---------------------+----------+-------
 public | lobos_migrations    | table    | baz
 public | foos                | table    | baz
 public | foos_id_seq         | sequence | baz

The output of \d foos
                                Table "public.foos"
 Column |         Type          |                     Modifiers  
--------+-----------------------+----------------------------------------------------
 id     | integer               | not null default nextval('foos_id_seq'::regclass)
 foo    | character varying(64) | 
Indexes:
    "foos_primary_key_id" PRIMARY KEY, btree (id)
    "foos_unique_foo" UNIQUE CONSTRAINT, btree (foo)
Check constraints:
    "foo" CHECK (length(foo::text) > 1)
Referenced by:
    TABLE "bars" CONSTRAINT "bars_fkey_foo_id" FOREIGN KEY (foo_id) REFERENCES foos(id) ON UPDATE CASCADE ON DELETE CASCADE

The output of \d foos_id_seq

```
    Sequence "public.foos_id_seq"
Column     |  Type   |        Value        
```

---------------+---------+---------------------
 sequence_name | name    | foos_id_seq
 last_value    | bigint  | 9
 start_value   | bigint  | 1
 increment_by  | bigint  | 1
 max_value     | bigint  | 9223372036854775807
 min_value     | bigint  | 1
 cache_value   | bigint  | 1
 log_cnt       | bigint  | 31
 is_cycled     | boolean | f
 is_called     | boolean | t
Owned by: public.foos.id
- Harold

**Comment by davejacobs** [comment]
Actually, I think the macro is okay. Misinterpeted the column type. Thanks for the info!
