### ISSUE TITLE
Column type

### ISSUE THREAD

**Issue by davejacobs** [budu/lobos#63]
How can I change a column's type in a migration? I've tried several variations of the following without success:

``` clojure
(defmigration change-categories
  (up []
    (alter :modify
      (table :posts
        (column :category (data-type :varchar 210)))))
  (down []
    (alter :modify
      (table :posts
        (column :category (data-type :varchar 255))))))
```

The error with this particular version is that 255 is expected to be vectorizable. I looked at the source code, and it looks like length is handled in a different way from things like `:default` and `:encoding`. Any pointers?

**Comment by schovi** [comment]
Today i was challenged by this too.
After lot of tries i finally found it!

``` clj
(alter :modify 
  (table :services 
    (varchar :description 5000 :not-null)))
```

**Comment by davejacobs** [comment]
Thanks!
