### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by chptx** [budu/lobos#66]

**Comment by budu** [comment]
Yes

**Comment by deadghost** [comment]
Is there a package we should favor over lobos?

**Comment by jalehman** [comment]
I've personally just started using
https://github.com/ckuttruff/clj-sql-up-- it's actively maintained and
much simpler in scope. So far, so good.

**Comment by chptx** [comment]
Ragtime: https://github.com/weavejester/ragtime
